spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secondarydb
    username: root           # Change as per your MySQL setup
    password: root   # Change as per your MySQL setup
  r2dbc:
    url: r2dbc:mysql://localhost:3306/secondarydb
    username: root           # Change as per your MySQL setup
    password: root   # Change as per your MySQL setup
  data:
    r2dbc:
      repositories:
        enabled: true

# Additional configuration can go here
logging:
  level:
    org.springframework: DEBUG  # Set log level to DEBUG for detailed logging
