spring:
  datasource:
    primary:
      url: jdbc:h2:mem:testdb
      username: sa
      password: password
      driver-class-name: org.h2.Driver
      hikari:
        pool-name: PrimaryPool
    secondary:
      url: jdbc:mysql://localhost:3306/secondarydb
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: SecondaryPool
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect